/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresupuestoRouteImport } from './routes/presupuesto'
import { Route as EscudosRouteImport } from './routes/escudos'
import { Route as DeudasRouteImport } from './routes/deudas'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as IndexRouteImport } from './routes/index'

const PresupuestoRoute = PresupuestoRouteImport.update({
  id: '/presupuesto',
  path: '/presupuesto',
  getParentRoute: () => rootRouteImport,
} as any)
const EscudosRoute = EscudosRouteImport.update({
  id: '/escudos',
  path: '/escudos',
  getParentRoute: () => rootRouteImport,
} as any)
const DeudasRoute = DeudasRouteImport.update({
  id: '/deudas',
  path: '/deudas',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/deudas': typeof DeudasRoute
  '/escudos': typeof EscudosRoute
  '/presupuesto': typeof PresupuestoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/deudas': typeof DeudasRoute
  '/escudos': typeof EscudosRoute
  '/presupuesto': typeof PresupuestoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/deudas': typeof DeudasRoute
  '/escudos': typeof EscudosRoute
  '/presupuesto': typeof PresupuestoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ajustes' | '/deudas' | '/escudos' | '/presupuesto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ajustes' | '/deudas' | '/escudos' | '/presupuesto'
  id: '__root__' | '/' | '/ajustes' | '/deudas' | '/escudos' | '/presupuesto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  DeudasRoute: typeof DeudasRoute
  EscudosRoute: typeof EscudosRoute
  PresupuestoRoute: typeof PresupuestoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presupuesto': {
      id: '/presupuesto'
      path: '/presupuesto'
      fullPath: '/presupuesto'
      preLoaderRoute: typeof PresupuestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escudos': {
      id: '/escudos'
      path: '/escudos'
      fullPath: '/escudos'
      preLoaderRoute: typeof EscudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deudas': {
      id: '/deudas'
      path: '/deudas'
      fullPath: '/deudas'
      preLoaderRoute: typeof DeudasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  DeudasRoute: DeudasRoute,
  EscudosRoute: EscudosRoute,
  PresupuestoRoute: PresupuestoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
