/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedPresupuestoRouteImport } from './routes/_authenticated/presupuesto'
import { Route as AuthenticatedLogrosRouteImport } from './routes/_authenticated/logros'
import { Route as AuthenticatedEscudosRouteImport } from './routes/_authenticated/escudos'
import { Route as AuthenticatedDeudasRouteImport } from './routes/_authenticated/deudas'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPresupuestoRoute =
  AuthenticatedPresupuestoRouteImport.update({
    id: '/presupuesto',
    path: '/presupuesto',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogrosRoute = AuthenticatedLogrosRouteImport.update({
  id: '/logros',
  path: '/logros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscudosRoute = AuthenticatedEscudosRouteImport.update({
  id: '/escudos',
  path: '/escudos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeudasRoute = AuthenticatedDeudasRouteImport.update({
  id: '/deudas',
  path: '/deudas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/deudas': typeof AuthenticatedDeudasRoute
  '/escudos': typeof AuthenticatedEscudosRoute
  '/logros': typeof AuthenticatedLogrosRoute
  '/presupuesto': typeof AuthenticatedPresupuestoRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/deudas': typeof AuthenticatedDeudasRoute
  '/escudos': typeof AuthenticatedEscudosRoute
  '/logros': typeof AuthenticatedLogrosRoute
  '/presupuesto': typeof AuthenticatedPresupuestoRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/deudas': typeof AuthenticatedDeudasRoute
  '/_authenticated/escudos': typeof AuthenticatedEscudosRoute
  '/_authenticated/logros': typeof AuthenticatedLogrosRoute
  '/_authenticated/presupuesto': typeof AuthenticatedPresupuestoRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ajustes'
    | '/deudas'
    | '/escudos'
    | '/logros'
    | '/presupuesto'
    | '/reportes'
    | '/auth/forgot'
    | '/auth/reset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ajustes'
    | '/deudas'
    | '/escudos'
    | '/logros'
    | '/presupuesto'
    | '/reportes'
    | '/auth/forgot'
    | '/auth/reset'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ajustes'
    | '/_authenticated/deudas'
    | '/_authenticated/escudos'
    | '/_authenticated/logros'
    | '/_authenticated/presupuesto'
    | '/_authenticated/reportes'
    | '/auth/forgot'
    | '/auth/reset'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presupuesto': {
      id: '/_authenticated/presupuesto'
      path: '/presupuesto'
      fullPath: '/presupuesto'
      preLoaderRoute: typeof AuthenticatedPresupuestoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logros': {
      id: '/_authenticated/logros'
      path: '/logros'
      fullPath: '/logros'
      preLoaderRoute: typeof AuthenticatedLogrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escudos': {
      id: '/_authenticated/escudos'
      path: '/escudos'
      fullPath: '/escudos'
      preLoaderRoute: typeof AuthenticatedEscudosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deudas': {
      id: '/_authenticated/deudas'
      path: '/deudas'
      fullPath: '/deudas'
      preLoaderRoute: typeof AuthenticatedDeudasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedDeudasRoute: typeof AuthenticatedDeudasRoute
  AuthenticatedEscudosRoute: typeof AuthenticatedEscudosRoute
  AuthenticatedLogrosRoute: typeof AuthenticatedLogrosRoute
  AuthenticatedPresupuestoRoute: typeof AuthenticatedPresupuestoRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedDeudasRoute: AuthenticatedDeudasRoute,
  AuthenticatedEscudosRoute: AuthenticatedEscudosRoute,
  AuthenticatedLogrosRoute: AuthenticatedLogrosRoute,
  AuthenticatedPresupuestoRoute: AuthenticatedPresupuestoRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
